const mongoose = require('mongoose');

const nhldb = new mongoose.Schema({
    team:{
        type:String,
        require:true,
    },
    season:{
        type:String,
        require:true,
    },
    gp:{
        type:String,
        require:true,
    },
    w:{
        type:String,
        require:true,
    },
   l:{
        type:String,
        require:true,
    },
    t:{
        type:String,
        require:true,
    },
    ot:{
        type:String,
        require:true,
    },
    p:{
        type:String,
        require:true,
    },
    pPorcent:{
        type:String,
        require:true,
    },
    rw:{
        type:String,
        require:true,
    },
    row:{
        type:String,
        require:true,
    },
   soWin:{
        type:String,
        require:true,
    },
    gf:{
        type:String,
        require:true,
    },
    ga:{
        type:String,
        require:true,
    },
    gfInGp:{
        type:String,
        require:true,
    },
    gaInGp:{
        type:String,
        require:true,
    },
    ppPorcent:{
        type:String,
        require:true,
    },
    pkPorcent:{
        type:String,
        require:true,
    },
    netPkPorcent:{
        type:String,
        require:true,
    },
    netPpPorcent:{
        type:String,
        require:true,
    },
    shotsGp:{
        type:String,
        require:true,
    },
    saGp:{
        type:String,
        require:true,
    },
    fowPorcent:{
        type:String,
        require:true,
    },
    dataAt:{
        type:String,
        require:true,
    }
});
module.exports=mongoose.model('nhl',nhldb);

